### ISSUE TITLE
Running the app

### ISSUE THREAD

**Issue by JSPhine** [dmandreev/simplestcntkapp#1]
Hi, thanks for writing the example!

I have a small question about running it.
After compiling the code (VS2013), I get a "Math.dll missing" error. I tried to solve it by moving the files in the CNTK release folder (that contains the math.dll), but then I got a "Runtime Error: R6030-CRT not initialized". 
Do you have an idea why this occurs and how to solve it? (I'm still learning app programming, so the question might be trivial. Sorry!)

Thanks in advance!

**Comment by dmandreev** [comment]
1) Add path to cntk bin folder to global %PATH% variable like set PATH=%PATH%;C:\Devel\CNTK\x64\Release\
2) Does your cntk.exe runs correctly? It seems that R6030-CRT  error is due to incorrect paths to MSVCR120.DLL, it need to be same for simplecnkapp.exe and math.dll, check it with "where MSVCR120.DLL"
